# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=255, unique=True)),
                ('user_id', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together=set([('user_id', 'apikey', 'active')]),
        ),
    ]
